# Mendefinisikan Versi Docker Compose
version: '3.8'

# Mendefinisikan Voulmes
volumes: 
  # Untuk Menyimpan Seluruh Data Dalam Database
  inventarisdb:

# Mendefinisikan Networks
networks:
  # Untuk Mengkoneksikan Antar Services
  inventarisapp:

# Mendefinisikan Services Yang Akan Dipakai
services:
  # Nama Service Untuk Web Server (nginx)
  nginx:
    # Gunakan Image Nginx Tag Alpine
    image: nginx:alpine
    # Kaitkan Folder Lokal Ke Container
    volumes: 
      # Folder Web
      - "./htdocs:/var/www"
      # Folder Konfigurasi Nginx
      - "./.build/nginx/conf.d:/etc/nginx/conf.d"
      - "./.build/nginx/nginx.conf:/etc/nginx/nginx.conf"
    # Ekspose Port
    ports: 
    # 80 (http://localhost)
      - "80:80" #inventaris laravel
      - "85:85" #inventaris ci
      - "443:443"
    # Jalankan Nginx Jika Service php Dan db Sudah Berjalan
    depends_on: 
      - php

    # Koneksikan Ke Network localapp
    networks: 
      - inventarisapp
    
    # Tambahkan Extra Host
    extra_hosts:
        - "host.docker.internal:host-gateway"

  # Nama Service Untuk PHP
  php:
    # Build Image Dengan Dockerfile Di Folder ./.build/php
    build: ./.build/php
    # Kaitkan Folder Lokal Ke Container
    volumes:
      # Jalankan PHP Di Semua Folder Web
      - "./htdocs:/var/www"
      # Folder Konfigurasi PHP 
      - "./.build/php/php.ini:/usr/local/etc/php/php.ini"

    # Koneksikan Ke Network localapp
    networks: 
      - inventarisapp

# Nama Service Untuk Database  
  db:
    # Gunakan Image mysql Tag latest
    image: mariadb:latest
    # Environment Yang Dibutuhkan mysql
    environment: 
      MARIADB_ROOT_PASSWORD: root
      MARIADB_PASSWORD: secret
      MARIADB_USER: homestead
    # Expose Port Agar Dapat Diakses Melalui Aplikasi MYSQL Client (phpmyadmin)
    ports: 
      - "3307:3306"
    # Simpan Semua Data Dalam Volumes localdb
    volumes: 
     - "inventarisdb:/var/lib/mariadb"
    # Koneksikan Ke Network localapp
    networks: 
      - inventarisapp
  
  # Nama Service Untuk PHPMYADMIN
  phpmyadmin:
    # Gunakan Image phpmyadmin
    image: phpmyadmin/phpmyadmin
    # Expose Port
    ports: 
      # Gunakan Port 8087 Untuk Mengakses phpmyadmin
      - "8080:80"
    # Koneksikan Ke Network localapp
    networks: 
      - inventarisapp